### ISSUE TITLE
Multi row strings make the debugger lines jump up and down

### ISSUE THREAD

**Issue by andreicristianpetcu** [firefox-devtools/debugger#8291] opened 2020-06-01 11:57 UTC
![multi_row](https://user-images.githubusercontent.com/922368/83406830-2713c980-a418-11ea-99ed-cab70f776dcf.gif)

**Comment by janodvarko** [comment] 2020-07-13 16:22
Thanks for the report!

@andreicristianpetcu Can you please provide a simple page we could use to see the bug on our machines?
It would be great help.

Thank you

**Comment by andreicristianpetcu** [comment] 2020-07-18 12:14
I think I hit the debugger bugs BINGO! :smile:
https://codepen.io/andreicristianpetcu/pen/JjGeNww?editors=0010 
![image](https://user-images.githubusercontent.com/922368/87852145-1e178280-c908-11ea-9189-674183bcc6a0.png)
Not sure if all these issues have the same cause but I'll list them here. If they are different issues, please report separate issues.

1) I was unable to reproduce the bug I mentioned with the pen I wrote but I got close: stepping over with f10 makes things jump and down. In the original bug mouse over on variables made it jump and down.

2) There is a huge gap between line 29 and 30 when I set a breakpoint at 31
![image](https://user-images.githubusercontent.com/922368/87852190-75b5ee00-c908-11ea-877b-6f3c28cb0d96.png)

3) Column breakpoint splits the console word `|>cons|>ole.|>log(myVar1);` 
![image](https://user-images.githubusercontent.com/922368/87852209-a26a0580-c908-11ea-837c-10df6339a4c3.png)

4) Cursor takes a lot of vertical space and you can even have multi line selection in a really strange way
![image](https://user-images.githubusercontent.com/922368/87852238-e8bf6480-c908-11ea-92a3-8c9b151ce8bc.png)
![image](https://user-images.githubusercontent.com/922368/87852241-ee1caf00-c908-11ea-9c67-83c8d1a32de2.png)

5) There are some really strange pieces of code that appear in this example that I did not write.
![image](https://user-images.githubusercontent.com/922368/87852264-2623f200-c909-11ea-9e4d-f68e62ca4122.png)
![image](https://user-images.githubusercontent.com/922368/87852266-2b813c80-c909-11ea-9fd7-b5a13e415e34.png)

@janodvarko

**Comment by janodvarko** [comment] 2020-08-24 11:29
Sorry for the delay!

I loaded the `https://codepen.io/andreicristianpetcu/pen/JjGeNww?editors=0010`
What should I do next?
Where exactly in the code I should break and step?

Honza

**Comment by andreiuipath** [comment] 2020-08-25 09:07
@janodvarko Thank you for looking into this.
Set a breakpoint at line 30.
Step over with F10.
![image](https://user-images.githubusercontent.com/50407920/91155430-83ab1b80-e6cb-11ea-91ac-4a36fb3cccd9.png)

**Comment by janodvarko** [comment] 2020-08-25 09:52
Thanks, I was able to reproduce the problem now.

I believe that this is duplicate of:
[Bug 1573562](https://bugzilla.mozilla.org/show_bug.cgi?id=1573562) - Prevent previews from flashing effect when stepping

The workaround here is to switch of the inline variable previews. You can use the Settings menu (see the gear icon in the top right corner of the Debugger panel)

Closing this report.

We are moving our bug tracking into Bugzilla anyway, so please file new bugs (if any) here:
https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Thanks,
Honza

**Closed by janodvarko** 2020-08-25 09:53 UTC
Labels: str-needed
