### ISSUE TITLE
Calls to 'Remove breakpoint' and 'Disable breakpoint' not reflected by breakpoint markers next to line numbers and breakpoint menu in Firefox 67

### ISSUE THREAD

**Issue by Archaeopteryx** [firefox-devtools/debugger#8062] opened 2019-03-03 13:41 UTC
This affects Firefox 67.0b12, tested on Windows 8.1

Calls to 'Remove breakpoint' and 'Disable breakpoint' not reflected by breakpoint markers next to line numbers and breakpoint menu.

Steps to reproduce:

- Open a web page, e.g. https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound
- Open the debugger.
- Open a file, e.g. the first file in the 'assets' folder.
- Right-click on a line and set a breakpoint.
- Right-click it again to remove the breakpoint.

Actual result: Breakpoint removed in the right sidebar, but marker next to line number remains.

Expected: Marker removed.

'Disable breakpoint' also doesn't update anything in the UI.

If one left clicks the line number and sets a breakpoint, calling the menu for that line after it will still offer to add a breakpoint instead of removing it.

**Comment by jasonLaster** [comment] 2019-03-04 21:35
@Archaeopteryx I believe this will be fixed soon by the column bp work
https://phabricator.services.mozilla.com/D21843

**Comment by janodvarko** [comment] 2019-12-12 13:21
I can't reproduce this anymore, closing.

Honza

**Closed by janodvarko** 2019-12-12 13:21 UTC
Labels: :bug: bug
