### ISSUE TITLE
Debugger does not refresh the source code on change.

### ISSUE THREAD

**Issue by johnfound** [firefox-devtools/debugger#6966] opened 2018-09-12 06:44 UTC
Firefox 62.0 (64-bit) on Manjaro Linux.

When I change the source code on the server and refresh the browser, the code on the page actually changes, but the code in the debugger is never reloaded. Closing the file in the debugger and selecting it again from the source tree does nothing. 

The only workaround is to open the same url in new tab. The source code in the new tab is loaded properly. Once.

Ctrl+F5 is not working, disabling cache is not working.

**Comment by johnfound** [comment] 2018-09-12 07:07
After creating new profile, the debugger works properly. But how to fix the problem in my default profile?

**Comment by jasonLaster** [comment] 2018-09-12 14:42
@johnfound that is disappointing. Could you provide some more context so that we can look into it. 

For instance, can you reproduce it by cloning this example -- http://dbg.glitch.me/

**Comment by johnfound** [comment] 2018-09-13 04:07
@jasonLaster  I didn't understood from your post what I have to do? What context? What to do on the above web site?

**Comment by jasonLaster** [comment] 2018-09-13 20:16
@johnfound -- http://dbg.glitch.me/ is a site we use to make new examples. feel free to make another example that we can use :)

**Comment by johnfound** [comment] 2018-09-15 06:00
On a "broken" FF profile the debugger does not work on every JS code. On a new created FF profile the debugger is working on every JS code. How this can be reproduced by creating example???

**Comment by loganfsmyth** [comment] 2020-07-09 19:21
Closing since this is old and there doesn't seem to be a reproducible case.

**Closed by loganfsmyth** 2020-07-09 19:21 UTC
