### ISSUE TITLE
TypeError: can't access dead object

### ISSUE THREAD

**Issue by Loirooriol** [firefox-devtools/debugger#5218] opened 2018-01-27 15:41 UTC
I couldn't open the debugger. The browser console showed

```
error occurred while processing 'listWorkers: TypeError: can't access dead object
Stack: matchWorkerDebugger@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/worker-list.js:30:12
getList@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/worker-list.js:59:11
onListWorkers@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/tab.js:640:12
onPacket@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1774:15
receiveMessage@resource://devtools/shared/base-loader.js -> resource://devtools/shared/transport/transport.js:761:7
Line: 30, column: 12  main.js:1637
	_unknownError resource://devtools/server/main.js:1637:5
	onPacket resource://devtools/server/main.js:1776:29
	receiveMessage resource://devtools/shared/transport/transport.js:761:7

onPacket threw an exception: Error: Server did not specify an actor, dropping packet: {"error":"unknownError","message":"error occurred while processing 'listWorkers: TypeError: can't access dead object\nStack: matchWorkerDebugger@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/worker-list.js:30:12\ngetList@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/worker-list.js:59:11\nonListWorkers@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/tab.js:640:12\nonPacket@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1774:15\nreceiveMessage@resource://devtools/shared/base-loader.js -> resource://devtools/shared/transport/transport.js:761:7\nLine: 30, column: 12"}
Stack: onPacket@resource://devtools/shared/base-loader.js -> resource://devtools/shared/client/debugger-client.js:857:9
send/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/transport/transport.js:570:13
exports.makeInfallible/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:14
exports.makeInfallible/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:14
Line: 857, column: 9
```
After restarting Firefox it seems to work again.

**Comment by jasonLaster** [comment] 2018-01-27 15:44
Thanks. Did you have workers in your tab?

**Comment by jasonLaster** [comment] 2018-01-27 15:45
Hey @juliandescottes I see you're doing some worker stuff lately. Does this ring a bell?

**Comment by Loirooriol** [comment] 2018-01-27 15:49
It happened in all tabs, even if they had no worker.

**Comment by lukaszsobek** [comment] 2018-01-28 10:36
This might be of help: https://blog.mozilla.org/addons/2012/09/12/what-does-cant-access-dead-object-mean/

**Comment by Loirooriol** [comment] 2018-02-26 15:13
Now I'm getting a similar error when trying to open the debugger in the browser toolbox:

```
error occurred while processing 'sources: TypeError: can't access dead object
Stack: createNonSourceMappedActor@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/utils/TabSources.js:312:1
createSourceActors/<@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/utils/TabSources.js:400:19
promise callback*createSourceActors@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/utils/TabSources.js:399:12
_discoverSources/<@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/thread.js:985:14
_discoverSources@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/thread.js:984:24
onSources@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/thread.js:990:12
onPacket@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1767:15
_onJSONObjectReady/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/transport/transport.js:482:11
exports.makeInfallible/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:14
exports.makeInfallible/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:14
Line: 312, column: 1

_unknownError resource://devtools/server/main.js:1630:5
	_queueResponse/responsePromise< resource://devtools/server/main.js:1648:25
	reject resource://devtools/shared/deprecated-sync-thenables.js:46:41
	then resource://devtools/shared/deprecated-sync-thenables.js:22:51
	resolve resource://devtools/shared/deprecated-sync-thenables.js:73:11
	reject resource://devtools/shared/deprecated-sync-thenables.js:47:16
```

**Comment by jasonLaster** [comment] 2018-03-14 20:52
I wonder if this bug is related to #5028.

@Loirooriol do you have sourcemaps turned off here?

**Comment by Loirooriol** [comment] 2018-03-14 21:51
I don't know how to toggle sourcemaps so probably I have the default.

**Comment by jasonLaster** [comment] 2018-03-14 22:35
thanks.  could you see if you get this with a fresh firefox profile?

**Comment by Loirooriol** [comment] 2018-03-14 22:45
The problem is that it happens very rarely, I can't reliably reproduce. But I think I got this on two different (non-fresh) profiles, so it doesn't seem caused by a random profile corruption.

**Comment by jasonLaster** [comment] 2018-03-14 23:32
thanks, i'll be on the look out for it.

Lastly, how often do you use watch expressions?

**Comment by Loirooriol** [comment] 2018-03-15 00:22
> how often do you use watch expressions?

Lately I rarely use them. Since they have been behaving very buggy, I got used to switching to the console and running the code there.

**Comment by icl7126** [comment] 2018-10-25 11:11
I'm seeing this issue several times a week and to solve it I have to close all Firefox instances - I'm add-on developer so I use `web-ext` tool to open another Firefox instance. And to fix this I have to close also my main Firefox.

``` error occurred while processing 'sources: TypeError: can't access dead object
Stack: createNonSourceMappedActor@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/utils/TabSources.js:311:5
createSourceActors/<@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/utils/TabSources.js:399:21
Line: 311, column: 5 main.js:1168
_unknownError
resource://devtools/server/main.js:1168:5
_queueResponse/responsePromise<
resource://devtools/server/main.js:1197:27
```

**Is there anything I can do to help you diagnose or fix this?**

**Comment by janodvarko** [comment] 2019-12-12 14:05
There is no reliable test case so, we can't reproduce that.
Closing.

But, if you see the bug again please, create a new report in Bugzilla:
https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza

**Closed by janodvarko** 2019-12-12 14:05 UTC
Labels: :bug: bug, not-actionable
