### ISSUE TITLE
Paused on * isn't shown for pause on next statement

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#6458] opened 2018-06-01 20:18 UTC
STR
- Open https://github.com/ (or right now)
- Hit Pause button to pause in random function

ER: See *Paused on Next Statement* (or something similar)
AR: No "Paused on" label

Stepping when paused like this will set the label correctly to "Pause while stepping".

<img width="160" alt="image" src="https://user-images.githubusercontent.com/8599/40861526-377d4d06-659e-11e8-8422-6ad81e4ba436.png">

**Comment by darkwing** [comment] 2018-06-01 22:22
I attempted to get a message to display during random pausing in FF 59 and I don't see a message, so unless I'm not repro'ing this properly, this has been an issue for a while.

**Comment by jasonLaster** [comment] 2018-07-02 18:15
This is where we would have our pause reasons
https://github.com/devtools-html/debugger.html/blob/release-67/src/utils/pause/why.js#L18

I'm going to move this to an enhancement as it is an unimplemented feature

**Comment by jasonLaster** [comment] 2018-08-03 14:36
We've got a WhyPaused component. It is also easy to pause and check the state with `dbg.selectors.getPauseReason` or something similar to that because everything is in the redux store

**Comment by janodvarko** [comment] 2020-08-28 12:59
I can't reproduce it anymore, closing.

Please file a new bug in Bugzilla if you still see the problem, thanks.
https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza

**Closed by janodvarko** 2020-08-28 12:59 UTC
Labels: :wave: help wanted, enhancement
