### ISSUE TITLE
[Frames] Selecting a frame flashes the sources tree

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7983] opened 2019-02-18 20:00 UTC
It looks like the sources tree tries to highlight the closest directory of the file and will show a blue highlight and then remove it?

![](http://g.recordit.co/mELdOLBOXC.gif)

**Comment by nagpalm7** [comment] 2019-03-01 05:30
@jasonLaster not just selecting a frame but sometimes selecting a source also flashes the same and also doesn't highlights the active source.

**Comment by jasonLaster** [comment] 2019-03-05 19:14
nice find. @nagpalm7

**Comment by janodvarko** [comment] 2019-12-13 12:54
I can't reproduce this one. There is no test case so, not sure if mine was good enough.

Closing but, please file in Bugzilla if you still see it.
https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger
(or provide STRs and I'll do the rest)

Thanks,
Honza

**Closed by janodvarko** 2019-12-13 12:54 UTC
Labels: :bug: bug, :wave: quality
