### ISSUE TITLE
[Reps] Inspector panel fails to expand with "document not defined" error

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#6401] opened 2018-05-23 22:18 UTC
STR:
- Install https://addons.mozilla.org/en-US/firefox/addon/angular-state-inspector/
- Navigate to https://angular-quickstart.glitch.me/
- Open Inspector, switch to new `State` panel
- Inspect an `ng-*` node
- Expand prototype in `State` panel

ER: Something expands

AR: Sidepanel goes white with error

<img width="1551" alt="image" src="https://user-images.githubusercontent.com/8599/40453870-7a6e162c-5e9b-11e8-9202-ee23dcf497ea.png">

**Comment by jasonLaster** [comment] 2018-05-23 22:34
@digitarald can you share a GIF

**Comment by nmicht** [comment] 2019-10-19 12:35
@digitarald I'm closing this for now. I was not able to reproduce this one.
Happy to re-open if you can provide a visual guide or another test case.

**Closed by nmicht** 2019-10-19 12:35 UTC
