### ISSUE TITLE
bogus sourcemap leads to being unable to prettify the file

### ISSUE THREAD

**Issue by karlcow** [firefox-devtools/debugger#7113] opened 2018-10-18 05:59 UTC
Original file 

![capture d ecran 2018-10-18 a 14 54 24](https://user-images.githubusercontent.com/505230/47133952-ecfac000-d2e5-11e8-973d-8f34f4a0ae0d.png)

Formatted file. It failed with the message:

> Error while fetching an original source: Error: "https://images.medicinenet.com/oocommon/js/20181004/legacy.js:formatted" is not in the SourceMap.
> Source URL: https://images.medicinenet.com/oocommon/js/20181004/legacy.js:formatted

![capture d ecran 2018-10-18 a 14 56 32](https://user-images.githubusercontent.com/505230/47133977-06037100-d2e6-11e8-9b1f-fda955df1767.png)

which is not extremely practical in this case :)

![capture d ecran 2018-10-18 a 14 58 29](https://user-images.githubusercontent.com/505230/47134056-511d8400-d2e6-11e8-9ee6-176bc0f6f7d2.png)

Site URL is https://www.medicinenet.com/acne/article.htm
Context https://github.com/webcompat/web-bugs/issues/19784

**Comment by karlcow** [comment] 2018-10-18 06:05
This seems to depends on 

```js
                        n[i].parentNode.insertBefore(d, n[i]), c.default.nextTick(function() {
                            Stickyfill.add(document.querySelectorAll("#apPgNum"))
                        }), _.forEach(["DOMContentLoaded", "load", "scroll", "resize", "popstate", "hashchange"], function(t) {
                            document.getElementById("content").addEventListener(t, _.framerateThrottle(function(t) {
                                if ((0, v.elementInView)(s, 300, 300)) {
                                    if (!o) {
                                        if (p) webmd.ads2.refresh({
                                            id: u,
                                            keys: {
                                                pg: e,
                                                LL: 1
                                            }
                                        });
                                        else {
                                            var n = {
                                                targets: (0, a.default)({}, window.ooAdTarget, {
                                                    pvid: window.s_pageview_id,
                                                    pg: e,
                                                    LL: 1
                                                }),
                                                id: u,
                                                pos: "2026",
                                                sizes: [
                                                    [300, 250],
                                                    [300, 253]
                                                ],
                                                blockCodes: window.ooAdTarget.blockCodes
                                            };
                                            webmd.ads2Consumer.defineAd(n), setTimeout(function() {
                                                l = n.slot
                                            }, 0), p = !0
                                        }
                                        o = !0, f = !0
                                    }
                                } else f && (googletag.pubads().clear([l]), f = !1), o = !1
                            }.bind(this)), !1)
                        }.bind(this))
```

StickyFill is defined in the same JS.

**Comment by AnshulMalik** [comment] 2018-10-18 10:10
@karlcow When I try to reproduce this, I don't see the buttons for format the file, how did you make it format?

**Comment by karlcow** [comment] 2018-10-18 15:30
@AnshulMalik when the `{}` is not visible, you can often ctrl+click on the tab title and there is a contextual menu with pretty print.

**Comment by karlcow** [comment] 2018-10-30 01:41
This makes it very hard to debug for example this site
https://readymag.com/

Try it with Chrome devtools, then try to access the sources with Firefox devtools

<img width="1186" alt="capture d ecran 2018-10-30 a 10 40 29" src="https://user-images.githubusercontent.com/505230/47690141-3fb27100-dc30-11e8-8916-7e2b547981b9.png">
<img width="1421" alt="capture d ecran 2018-10-30 a 10 40 50" src="https://user-images.githubusercontent.com/505230/47690155-4a6d0600-dc30-11e8-98af-6721bcf9d156.png">

**Comment by jasonLaster** [comment] 2019-01-07 21:31
@karlcow could you re-test it? it looks like sourcemaps might be loading...

<img width="782" alt="screen shot 2019-01-07 at 4 30 40 pm" src="https://user-images.githubusercontent.com/254562/50794622-a049d400-1299-11e9-828e-f8b2c4f1bd5c.png">

**Comment by karlcow** [comment] 2019-01-08 01:13
Using Nightly 66.0a1 (2019-01-07) (64-bit) on macos 10.14.2

1. Go to https://www.medicinenet.com/acne/article.htm
2. Open the devtools debugger
3. Go to `images.medicinenet.com/oocommon/js/20181004/legacy.js` in debugger

Actual: 
minified script. no braces for prettifying.

<img width="1193" alt="capture d ecran 2019-01-08 a 10 08 58" src="https://user-images.githubusercontent.com/505230/50803581-9c679180-132d-11e9-9889-fc12d8cb0f05.png">

Checking my settings in devtools.

<img width="1193" alt="capture d ecran 2019-01-08 a 10 10 48" src="https://user-images.githubusercontent.com/505230/50803592-b1442500-132d-11e9-9812-7e55be3c13f3.png">

Trying the crtl+click method.

<img width="309" alt="capture d ecran 2019-01-08 a 10 12 41" src="https://user-images.githubusercontent.com/505230/50803662-f700ed80-132d-11e9-9061-69f21ca7c531.png">

not available.

**Comment by karlcow** [comment] 2019-01-08 01:14
@jasonLaster we are not looking at the same source. :)

**Comment by qguv** [comment] 2019-05-01 12:19
This behavior persists in Firefox 66.0.3 on Fedora 29 for amd64.

One workaround is to disable source map support in settings:

![Screenshot from 2019-05-01 14-12-36](https://user-images.githubusercontent.com/553637/57016610-417ae280-6c1b-11e9-9c22-cd8418abb06a.png)

The pretty-print functionality will now be available again:

![Screenshot from 2019-05-01 14-12-51](https://user-images.githubusercontent.com/553637/57016754-2eb4dd80-6c1c-11e9-90f9-cd9a3215f582.png)

**Comment by jasonLaster** [comment] 2019-05-02 11:20
Thanks for the update @karlcow @qguv

**Comment by loganfsmyth** [comment] 2020-07-09 19:22
Closing in favor of https://bugzilla.mozilla.org/show_bug.cgi?id=1361271

**Closed by loganfsmyth** 2020-07-09 19:22 UTC
Labels: :bug: bug
