### ISSUE TITLE
Scopes stuck in Loading for minutes (or Unavailable State)

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#8057] opened 2019-03-01 22:48 UTC
STR:
- Open https://meta.discourse.org/
- In Debugger, enable _Pause on any URL_ in _XHR Breakpoints_
- Click the first header

AR (50% chance to hit one or the other bug):
1. Scopes stuck in `Loading …` state for 3+ minutes (on a MBP)
2. Scopes show `Scopes unavailable`
   1. Sometimes: Source doesn't load and gets stuck in `Loading …`

![image](https://user-images.githubusercontent.com/8599/53670529-e5eaa380-3c2f-11e9-9426-f6c17d142b24.png)

Profile shows a worker churning: https://perfht.ml/2Xy1qEQ

**Comment by digitarald** [comment] 2019-03-02 00:23
Full profiler for 3min, lots of JS: https://perfht.ml/2SxHDSp

![image](https://user-images.githubusercontent.com/8599/53673732-39fc8480-3c3e-11e9-92ff-60859d72983c.png)

**Comment by bhackett1024** [comment] 2019-03-06 02:40
That profile is really helpful, thanks.  The problem is that getUniqueIdentifiers() in the parser worker is O(N^2) instead of O(N).  Fixing this changes the time taken in this function from 112 seconds to 68 milliseconds.  I'll create a PR.  It still takes a little while to even get to the getUniqueIdentifiers() call (we're probably parsing some big file) but afterwards the mapped sources appear quickly.

**Comment by jasonLaster** [comment] 2019-03-06 13:52
I'm a bit concerned that we spend 20s legitimately in `getSymbols`. This makes me wonder if we should avoid calling getSymbols in extreme cases or shard the parser worker...

**Comment by bhackett1024** [comment] 2019-03-06 14:53
I'm going to continue looking at this testcase.  There isn't any reason we should need to spend this much time parsing (note that the browser does not need 20s to load the website).

**Comment by janodvarko** [comment] 2019-12-12 13:30
The original issue is fixed so, closing the report.

@bhackett1024: let me know if any remaining work should be reported in Bugzilla. I can do it.

Honza

**Closed by janodvarko** 2019-12-12 13:30 UTC
Labels: :bug:  bug: P1, :bug: bug
