### ISSUE TITLE
same keyboard shortcut (⌘;) is used for two functions: "step in" and "go to line"

### ISSUE THREAD

**Issue by juliandescottes** [firefox-devtools/debugger#6946] opened 2018-09-07 06:25 UTC
From https://bugzilla.mozilla.org/show_bug.cgi?id=1488662

same keyboard shortcut (⌘;) is used for two functions: "step in" and "go to line".

steps to reproduce:
1. set a breakpoint and hit the breakpoint with the debugger
2. press ⌘; to step into a function

expected:
- step-in action performed
- nothing else

actual:
- step-in action performed
- the "search sources" popup is shown, with ":" populated as the query string; ie. the "go to line" feature

note the ⌘; and ⌘' shortcuts are quite useful on macos, where F11 is mapped to "show desktop" by default.

**Comment by jasonLaster** [comment] 2018-09-07 12:38
Thanks, I believe this is a duplicate, but i'm not sure where. 

CC @digitarald, @darkwing curious what you think we should do

**Comment by juliandescottes** [comment] 2019-01-08 21:30
@jasonLaster I still reproduce this on the latest Nightly.

If I am on a breakpoint, pressing `cmd + ;` will both open the search input and jump to the next line. The PR from Greg was not merged, so this is not fixed currently.

**Comment by cpeterso** [comment] 2019-02-12 18:01
The step-out keyboard shortcut `⌘:` (Cmd + Shift + ;) also opens the "Go to line" popup.

**Comment by chujunlu** [comment] 2019-03-27 20:09
Hi all! I can reproduce the behavior @juliandescottes and @cpeterso mentioned above. I read the inactive PR of this issue. Could I pick it up from where it left off? Thanks.

**Comment by jasonLaster** [comment] 2019-04-15 13:00
@chujunlu go for it

**Comment by chujunlu** [comment] 2019-04-19 18:51
Hey @jasonLaster, I submitted a patch to Phabricator. It fixes the issue for macOS but not works perfectly for Windows and Linux. I'm facing a dilemma for Windows/Linux, which I described in https://phabricator.services.mozilla.com/D26256. It would be helpful to hear your inputs if you have time. Thanks :)

**Comment by janodvarko** [comment] 2019-12-12 13:45
This seems to be fixed (testing on Win), closing.

Honza

**Closed by janodvarko** 2019-12-12 13:45 UTC
Labels: :bug: bug, accessibility

**Comment by gregtatum** [comment] 2019-12-18 16:23
I can confirm it is fixed on Mac as well.
