### ISSUE TITLE
Mouse scrolling in "Go to file" jumps back to top 

### ISSUE THREAD

**Issue by jnachtigall** [firefox-devtools/debugger#7483] opened 2018-12-11 10:42 UTC
STR:
1. CTRL+P and enter a search that will show up enough results to have scrollbar, maybe just a single letter like `a`
2. Use mouse to scroll **down**

AR:
Scrollbar always jump back to top automatically (I guess back to the first selected item)

ER:
Mouse scrolling should work and if I scroll down this position should be kept. FWIW the keyboard arrows keys UP / DOWN work

Here's what it behaves like at the moment:
![debugger_scroll](https://user-images.githubusercontent.com/3307404/49795131-7dc7a800-fd39-11e8-8953-799c883e578a.gif)

GitHub's "Related issues" proposes this to be the same like #5660 which it is. But I am using Today's Nightly Firefox 66

**Comment by jnachtigall** [comment] 2018-12-11 10:52
In fact the QuickOpenModal always jumps to selected (highlighted) item. If you navigate with UP / DOWN keys to a file in the middle of the modal and then use the mouse scrolling then it also always jumps back to highlighted / selected item.

Using Windows.

**Comment by darkwing** [comment] 2019-02-11 20:09
I unfortunately cannot reproduce on Mac

**Comment by darkwing** [comment] 2019-02-20 16:27
@jnachtigall Could you test this again in Nightly?  Are you still seeing the issue?  I could not reproduce.

**Comment by darkwing** [comment] 2019-03-01 20:06
I can't duplicate this on Windows or Mac, so closing.

**Closed** 2019-03-01 20:06 UTC
Labels: :wave: quality, :wave: quality-p1

**Comment by fvsch** [comment] 2019-03-13 16:01
I can reproduce with Firefox Nightly on Linux.

STR:
1. Go to a GitHub issue, say https://github.com/firefox-devtools/ux/issues/41
2. Open Debugger and hit Ctrl+P. There should be roughtly 100 files listed.
3. Scroll down _with the mouse or trackpad_, and wait a second or two.

Current result:
- The list scrolls back up to show the highlighted result (e.g. the first one).
- It's virtually impossible to look at the end of the list.

When scrolling with the up/down keyboard keys, things work better.

It looks like we are periodically scrolling the list so that the currently selected item is centered in the list. We do that after up/down keys, which is alright, but seem to be doing it periodically (on a timer or render?), or maybe after a scroll event.

**Comment by fvsch** [comment] 2019-03-13 16:12
An important step to reproduce: there must be a list of files displayed, with one file selected.

Apparently if you hit Ctrl+P, you get a text input and no list until you type something. What more, after typing a query like "js", while I get a lot of results I don't always have the first result selected. It's also possible to move the selection offset in the negatives or out of bonds!

**Comment by fvsch** [comment] 2019-03-13 16:24
Another good page to test:
https://firefox-dev.tools/debugger-examples/examples/500-sources.html
