### ISSUE TITLE
Navigating callstack conflicts with search result focussing

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#6747] opened 2018-08-03 20:27 UTC
STR:
- Open Debugger on https://bl.ocks.org/ColinEberhardt/raw/6ceb7ca74aabac9c8534d7120d31b382/
- Open JS file
- Search for `wasm.`
- Pause and step until it hits WASM code (look for `wasm2` methods)
- Step between WASM code and JS in callstack

25% speed:

![screenflow](https://user-images.githubusercontent.com/8599/43664164-c5c1fdd8-9720-11e8-8723-dd3bec72c376.gif)

**Comment by janodvarko** [comment] 2018-08-30 13:38
I can nicely reproduce this issue.

Note that the issue happens only when the user switches from WASM file to JS file. I.e. instead of navigating to the (clicked) frame location in the JS file the current search location is selected. When the users switches between to JS frames it works well.

Honza

**Comment by darkwing** [comment] 2018-10-13 21:56
This could be a bit tough; you may want to look at the "help wanted" and "good first issue" labels 👍

**Comment by navgurukul-shivani18** [comment] 2018-10-25 20:36
I really want to solve this issue, had been trying to lead on where the issue is coming from the code. I tried alot, but, couldn't find a way to solve it. I thought I should be independent by now

**Comment by navgurukul-shivani18** [comment] 2018-10-26 05:17
@AnshulMalik Can you please help me finding any good bug to work on? Please!

**Comment by YisraelV** [comment] 2019-01-24 18:11
Copying from slack: 

currently if there is some text in the search box, and user navigates between files, the search results are updated and the document is scrolled to the first result.

This issue  is about when the user navigates using the stack-frames panel. The expected behavior is  scrolling to the executed line, but the actual behavior is scrolling to the first search result.

In my opinion this is a more general problem: when the user navigates to a file it should always start at the first line, regardless if it's with quick-open, clicking on tab or selecting a stack-frame. The user probably just wanted to see the file and there is no reason to scroll to the first result.

I checked the behavior of two other code editors:
1. in vscode when navigating to a file the search results are updated, but  the scroll-to-first-result is not triggered.
2. Chrome devtools only shows a message "n results" (e.g. "5 results")" but without scrolling and without showing the current result message (e.g. 2 out of 4) only when the user retriggers the search (by pressing enter inside the search bar) the first result is selected and scroll to.

I find Chrome's to be the best user experience. Please tell me what you think, and if others agree with me I will try to implement it in the code.

Thanks for your help!

**Comment by jasonLaster** [comment] 2019-01-24 19:51
I agree @YisraelV. Chrome's approach is nice

**Comment by darkwing** [comment] 2019-04-26 14:57
Just landed fix in MC.

**Closed by darkwing** 2019-04-26 14:57 UTC
Labels: :bug:  bug: P1, :construction_worker_woman:  in progress, :wave: quality, :wave: quality-p1
