### ISSUE TITLE
Paused state on refresh keeps the Debugger in half-loaded state

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#6457] opened 2018-06-01 19:53 UTC
Firefox 62.0a1 (2018-06-01) (64-bit)

STR
- Opened perf-html.io
- Set a breakpoint in `webpack/src/index.js`
- Hard refresh, breakpoint gets hit
- Soft refresh a few times

ER: Page loads and breakpoint gets hit
AR: Half-loaded state for debugger, with correctly paused panel-tab icon but incomplete UI (no sources or breakpoints)

No errors in browser console.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/8599/40860544-a0b2d970-659a-11e8-8e53-f42384d2202e.png">

**Comment by darkwing** [comment] 2018-06-02 01:09
I could reproduce this just as described.  I pressed "Resume" and nothing happened.  I then refreshed again and the breakpoint was hit again and the debugger continued to work properly.

**Comment by darkwing** [comment] 2018-06-04 13:59
@jimblandy Could this be a server bug?  Do you have any insights as to what could cause this?

**Comment by jasonLaster** [comment] 2018-08-23 20:37
Just tried this by refreshing fairly quickly and got an error here:

```js

function getPendingBreakpointsForSource(state, source) {
  // source is not defined
  const sources = (0, _sources.getSourcesByURL)(state, source.url);

  if (sources.length > 1 && (0, _devtoolsSourceMap.isGeneratedId)(source.id)) {
    // Don't return pending breakpoints for duplicated generated sources
    return [];
  }

  return getPendingBreakpointList(state).filter(pendingBreakpoint => pendingBreakpoint.location.sourceUrl === source.url);
}

```

**Comment by digitarald** [comment] 2018-10-22 21:47
Reproduced on recent Nightly with fresh profile, happened 2 times in this session:

![screenflow](https://user-images.githubusercontent.com/8599/47321301-4118e380-d609-11e8-9173-22cfd11d434f.gif)

Profile recorded while loading was stuck: https://perfht.ml/2S9wmsv

**Comment by janodvarko** [comment] 2020-08-25 10:20
I can't reproduce that anymore, closing.

We are moving our bug tracking into Bugzilla, so please report bugs here:
https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Thanks,
Honza

**Closed by janodvarko** 2020-08-25 10:20 UTC
Labels: :bug:  bug: P1
